on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pytest and reqeust
      run: |
        python -m pip install --upgrade pip
        pip install requests pytest boto3
    - name: Run component tests
      run: |
        pytest

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: test-results.xml

    - name: Publish Test Report Summary
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Pytest Results
        path: test-results.xml
        reporter: java-junit
